### ISSUE TITLE
Grabbing a logo automatically from Newgrounds

### ISSUE THREAD

**Issue by VFDan** [FlashpointProject/fpcurator#1]
After doing some reverse-engineering, I was able to figure out the file structure behind the logos of games on Newgrounds. Let's take a game, Street Hugger. The link (that gets put in fpcurator) is https://www.newgrounds.com/portal/view/785032. The important part of this is the Game ID, `785032`. You can then get the game image by putting it in this format: 
https://picon.ngfiles.com/[id-t]/flash_ [id] _card.png (it's still Flash for HTML5 games); `id` is just the Game ID, in this case `785032`; `id-t` is the Game ID founded down to the thousands place, so 785000 for Street Hugger. Thus, the logo for Street Hugger is located at https://picon.ngfiles.com/785000/flash_785032_card.png.

Logos are saved as `logo.png` outside the `content` folder.

**Comment by mathgeniuszach** [comment]
Neat! I'll add this to the site definition for the next release.

**Comment by mathgeniuszach** [comment]
![image](https://user-images.githubusercontent.com/40220050/111566582-cae62000-8773-11eb-8a7e-ccd9b63cf0c8.png)
Code is simple too (of course, error handling requires another method) :)

**Comment by VFDan** [comment]
Thanks!
