### ISSUE TITLE
FPCurator sometimes doesn't register line breaks in original descriptions

### ISSUE THREAD

**Issue by VCheesey** [FlashpointProject/fpcurator#14]
I've noticed this specifically when auto-curating some stuff from Itch.io. This issue only happens sometimes (probably only with certain ways of coding line breaks in html?) This sometimes results in original descriptions being compressed into a single awkward paragraph.

Example: https://seansleblanc.itch.io/pico-8-styler

Expected original description:
> A tool for generating simple customized pages for PICO-8 games with a few bonus features.
> 
> Note: relies on a PHP script on an external server. I've included ultrabrite's input test cartridge ("padtest") on the server as well, so you can use it to test if you'd like.
> 
> Source available on GitHub.

Actually generated original description:
> A tool for generating simple customized pages for PICO-8 games with a few bonus features.Note: relies on a PHP script on an external server. I've included ultrabrite's input test cartridge ("padtest") on the server as well, so you can use it to test if you'd like.Source available on GitHub.

**Comment by mathgeniuszach** [comment]
This would be an issue with the Itch.IO site definition. Let me take a look.
